services:
  - type: web
    name: deboyes-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py migrate && python seed_zones.py && python manage.py collectstatic --no-input
    startCommand: cd backend && gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: CORS_ALLOWED_ORIGINS
        value: https://frontend-production-b947.up.railway.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://frontend-production-b947.up.railway.app
      - key: DEBUG
        value: "False"
      - fromGroup: deboyes-common
