# Generated by Django 4.2.29 on 2026-04-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_assigned_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('ready', 'Ready'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
