# Generated by Django 4.2.29 on 2026-04-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('ready', 'Ready'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered')], default='new', max_length=20),
        ),
    ]
