# Generated by Django 4.2.29 on 2026-04-10 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stop_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeliveryBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='available', max_length=20)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_time', models.IntegerField(default=30, help_text='In minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliverybatch'),
        ),
    ]
