# Generated by Django 4.2.29 on 2026-04-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='window_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='priority_score',
            field=models.FloatField(default=0),
        ),
    ]
