# Generated by Django 4.2.29 on 2026-04-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_deliverybatch_window_expires_at_order_lat_order_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
