# Generated by Django 6.0.4 on 2026-04-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_approved_user_current_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('rider', 'Rider'), ('admin', 'Admin')], max_length=10),
        ),
    ]
