# Generated by Django 4.2.29 on 2026-04-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='max_batch_size',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
