# Generated by Django 5.2.13 on 2026-04-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_logincode_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
