# Generated by Django 6.0.4 on 2026-04-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
